# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2018-01-25 14:39:00'),
            preserve_default=False,
        ),
    ]
